SELECT ep.ID_ENTIDAD_PACIENTE, ep.VALOR, ep.FECHA_VICULACION, ep.FECHA_PAGO, ep.ACTIVO,
p.ID_PACIENTE, p.NOMBRES, p.APELLIDOS, p.IDENTIFICACION, p.DIRECCION, p.TELEFONO, p.EMAIL,
e.ID_ENTIDAD, e.EPS
FROM ENTIDAD_PACIENTE ep
  INNER JOIN PACIENTE p ON ep.ID_PACIENTE = p.ID_PACIENTE
  INNER JOIN ENTIDAD e ON ep.ID_ENTIDAD  = e.ID_ENTIDAD
WHERE p.IDENTIFICACION =:docIdentificacionPaciente;